import { zodToJsonSchema } from "zod-to-json-schema";
import {
  ActionHintSchema,
  AdapterMutationMappingSchema,
  ApplyIntentOutcomeSchema,
  ApplyPlanSchema,
  ApprovalDecisionSchema,
  ArtifactKindSchema,
  CapabilityContractSchema,
  CanonicalMutationDomainSchema,
  ContextPacketSchema,
  ConversationAnchorSchema,
  FollowUpRequestSchema,
  MutationIntentSchema,
  OpenTagEventSchema,
  OpenTagRunResultSchema,
  OpenTagRunSchema,
  ProposalLineageSchema,
  RunAdmissionDecisionSchema,
  RunEventImportanceSchema,
  RunEventSchema,
  RunEventVisibilitySchema,
  PolicyResolutionSchema,
  SuggestedChangesSnapshotSchema,
  SuccessMetricNameSchema,
  WorkItemReferenceSchema,
  WorkThreadSchema
} from "./schema.js";

export const OpenTagJsonSchemas = {
  OpenTagEvent: zodToJsonSchema(OpenTagEventSchema, "OpenTagEvent"),
  OpenTagRun: zodToJsonSchema(OpenTagRunSchema, "OpenTagRun"),
  OpenTagRunResult: zodToJsonSchema(OpenTagRunResultSchema, "OpenTagRunResult"),
  RunAdmissionDecision: zodToJsonSchema(RunAdmissionDecisionSchema, "RunAdmissionDecision"),
  FollowUpRequest: zodToJsonSchema(FollowUpRequestSchema, "FollowUpRequest"),
  WorkItemReference: zodToJsonSchema(WorkItemReferenceSchema, "WorkItemReference"),
  ConversationAnchor: zodToJsonSchema(ConversationAnchorSchema, "ConversationAnchor"),
  WorkThread: zodToJsonSchema(WorkThreadSchema, "WorkThread"),
  ContextPacket: zodToJsonSchema(ContextPacketSchema, "ContextPacket"),
  RunEventVisibility: zodToJsonSchema(RunEventVisibilitySchema, "RunEventVisibility"),
  RunEventImportance: zodToJsonSchema(RunEventImportanceSchema, "RunEventImportance"),
  RunEvent: zodToJsonSchema(RunEventSchema, "RunEvent"),
  ArtifactKind: zodToJsonSchema(ArtifactKindSchema, "ArtifactKind"),
  AdapterMutationMapping: zodToJsonSchema(AdapterMutationMappingSchema, "AdapterMutationMapping"),
  CapabilityContract: zodToJsonSchema(CapabilityContractSchema, "CapabilityContract"),
  PolicyResolution: zodToJsonSchema(PolicyResolutionSchema, "PolicyResolution"),
  ProposalLineage: zodToJsonSchema(ProposalLineageSchema, "ProposalLineage"),
  SuccessMetricName: zodToJsonSchema(SuccessMetricNameSchema, "SuccessMetricName"),
  ActionHint: zodToJsonSchema(ActionHintSchema, "ActionHint"),
  CanonicalMutationDomain: zodToJsonSchema(CanonicalMutationDomainSchema, "CanonicalMutationDomain"),
  MutationIntent: zodToJsonSchema(MutationIntentSchema, "MutationIntent"),
  SuggestedChangesSnapshot: zodToJsonSchema(SuggestedChangesSnapshotSchema, "SuggestedChangesSnapshot"),
  ApprovalDecision: zodToJsonSchema(ApprovalDecisionSchema, "ApprovalDecision"),
  ApplyPlan: zodToJsonSchema(ApplyPlanSchema, "ApplyPlan"),
  ApplyIntentOutcome: zodToJsonSchema(ApplyIntentOutcomeSchema, "ApplyIntentOutcome")
} as const;
