blank_issues_enabled: false
contact_links:
  - name: "\U0001F680 Feature Request"
    url: https://github.com/QwenLM/Qwen-AgentWorld/discussions/categories/polls
    about: Create a poll and see if others are interested in a new feature as well
  - name: "\U0001F64F Question"
    url: https://github.com/QwenLM/Qwen-AgentWorld/discussions/categories/q-a
    about: Quick question, what/when/where/why/how ...
  - name: "\U0001F4AC General Discussion"
    url: https://github.com/QwenLM/Qwen-AgentWorld/discussions/categories/general
    about: Discuss in general
